### ISSUE TITLE
"0 hosts added to hosts list"

### ISSUE THREAD

**Issue by shino333** [Ettercap/ettercap#985]
Hi,
Being new to ettercap and mitm, I mitm OK using kali live USB but for some reason I can't wrap my head around, I can't using my kali installation as ettercap won't add any host to the hosts list.
Yet, it's the same network, and "arp -a" always returns 2 hosts.
Any ideas what could be missing/broken in my kali installation (rolling 2019.4)?

arp -a
? (192.168.1.3) at ##1 [ether] on eth1
_gateway (192.168.1.254) at ##2 [ether] on eth1

sudo ettercap -T -i eth1 -M arp:remote ##2/192.168.1.254// ##1/192.168.1.3//

ettercap 0.8.2 copyright 2001-2015 Ettercap Development Team

Listening on:
  eth1 -> #####
	  192.168.1.2/255.255.255.0
	  ####
	  ####

Privileges dropped to EUID 0 EGID 0...

  33 plugins
  42 protocol dissectors
  57 ports monitored
20388 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services
Lua: no scripts were specified, not starting up!

Scanning for merged targets (2 hosts)...

* |==================================================>| 100.00 %

0 hosts added to the hosts list...

**Comment by koeppea** [comment]
This is due to a meanwhile known issue with a newer version of libpcap 
which is a dependency of Ettercap.

The issue is already fixed, but not yet backported into Kali. For you it 
means that you need to remove the installed binary version of ettercap 
and compile ettercap from Github source.

Checkout our Wiki to find hint how doing this.

In the meantime (since you're the 3rd guy with the same issue), I'll 
reach out to the Kali maintainer asking if the latest changes can be 
backported into the binary distribution version.

**Comment by uemahra** [comment]
Hi koeppea,

I have the exactly same issue like him.
And I downloaded the 0.8.3, cmake .., make install, the problem is still there. And I haven't find related hint in wiki page.

**Comment by hjie** [comment]
me too, kali 2019.4 and ettercap 0.8.3, 0 hosts found

**Comment by DepressedAdmin** [comment]
Hi
me too and when i try compile source , i get the following error:
-- No GTK_BUILD_TYPE defined, default is GTK3
CMake Error at cmake/Modules/FindGTK3.cmake:365 (message):
  Could not find GTK3 include directory
Call Stack (most recent call first):
  cmake/Modules/EttercapLibCheck.cmake:53 (find_package)
  CMakeLists.txt:106 (include)



PLZ HELP

**Comment by koeppea** [comment]
Let me do up a little screencast covering this topic.

**Comment by koeppea** [comment]
> strange! i did renamed etter.mdns and etter.dns but still gets errors"

This is an indication that the old installation hasn't been purged completely.

**Comment by badbn1** [comment]
> 
> 
> Hi
> me too and i try apt-get purge ettercap and successfuly install it from source and again same problem here is the output:
> ettercap 0.8.3 copyright 2001-2019 Ettercap Development Team
> 
> Listening on:
> eth0 -> 00:0C:29:E0:35:7D
> 192.168.1.2/255.255.255.0
> fe80::20c:29ff:fee0:357d/64
> 
> SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
> Privileges dropped to EUID 65534 EGID 65534...
> 
> mdns_spoof: etter.mdns:52 Invalid IPv4 or IPv6 address
> mdns_spoof: etter.mdns:54 Invalid IPv4 or IPv6 address
> mdns_spoof: etter.mdns:61 Invalid IPv4 or IPv6 address
> dns_spoof: etter.dns:71 Invalid IPv4 or IPv6 address
> dns_spoof: etter.dns:78 Invalid IPv4 or IPv6 address
> dns_spoof: etter.dns:81 Invalid IPv4 or IPv6 address
> dns_spoof: etter.dns:90 Invalid IPv4 or IPv6 address
> dns_spoof: etter.dns:99 Invalid IPv4 or IPv6 address
> dns_spoof: etter.dns:112 Invalid IPv4 or IPv6 address
> 34 plugins
> 42 protocol dissectors
> 57 ports monitored
> 24609 mac vendor fingerprint
> 1766 tcp OS fingerprint
> 2182 known services
> 
> Scanning for merged targets (2 hosts)...
> 
>     * |==================================================>| 100.00 %
> 
> 
> 0 hosts added to the hosts list...
> 
> FATAL: ARP poisoning needs a non empty hosts list.
> 
> "strange! i did renamed etter.mdns and etter.dns but still gets errors"
> 
> PLZ HELP

As the koeppea said, you need to remove the installed binary version of ettercap
and compile ettercap from Github source. To do so:

sudo apt-get purge --auto-remove ettercap-graphical
sudo apt-get purge --auto-remove ettercap-common
git clone https://github.com/Ettercap/ettercap.git
cd ettercap
mkdir build
cd build
cmake ../
make
make install

**Comment by koeppea** [comment]
You see the warning messages with dns_spoof? This is already fixed in master. So I wonder which source you’re installed. Have you checked when you purged ettercap that nothing was left over? E.g searching for ‘*ettercap*’.

**Comment by koeppea** [comment]
I've created a [screencast](https://youtu.be/W3S1scJPy1Q) addressing this issue.
I think when you follow this Howto, you have at least a way to continue.
The issue in already fixed as demonstrated in the video.
Feel free to reopen but then with providing the debug information described in the above linked video.

**Comment by Archilla1** [comment]
Hi to you all! I have issue were I only see one address. I have uninstalled and reinstalled from source as @koeppea showed here, but still same issue. 

ettercap 0.8.4-rc copyright 2001-2020 Ettercap Development Team

Listening on:
  eth0 -> **Info deleted**
          172.17.214.237/255.255.240.0
          fe80::215:5dff:fee8:1cde/64

SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
Privileges dropped to EUID 65534 EGID 65534...

  34 plugins
  42 protocol dissectors
  56 ports monitored
28230 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services

Randomizing 4095 hosts for scanning...
Scanning the whole netmask for 4095 hosts...
* |==================================================>| 100.00 %

1 hosts added to the hosts list...
Starting Unified sniffing...


Text only Interface activated...
Hit 'h' for inline help

                                                                                                                          
                                                                                                                          
Hosts list:                                                                                                               
                                                                                                                          
1)      172.17.208.1    00:15:5D:E8:17:DD                                                                                 
                                                                                                                          
                                                                                                                          
Closing text interface...                                                                                                 
                                                                                                                          
                                                                                                                          
Terminating ettercap...                                                                                                   
Unified sniffing was stopped.




Is is something to do with my NIC that I need to enable? 
Thanks for the help!

**Comment by koeppea** [comment]
Well the 0 hosts found issue was different as there wouldn't have been found any host. Not even one.

Since your problem is different, please open a new issue providing the same info plus the ettercap debug log file which can be found the directory ettercap has been executed.

**Comment by Archilla1** [comment]
ok thank you! 
I am new at this and I apologize for that, but how can I find it? just keep doing cd until I reach Build dir then ls?
